shell = "zsh"
apply = ["defer"]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[templates]
defer = """{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}"""

[plugins.compinit]
# from https://gist.github.com/ctechols/ca1035271ad134841284
inline = '''
_compinit() {
  local re_initialize=0
  for match in .zcompdump*(.Nmh+24); do
    re_initialize=1
    break
  done

  autoload -Uz compinit
  if [ "$re_initialize" -eq "1" ]; then
    compinit
    # update the timestamp on compdump file
    compdump
  else
    # omit the check for new functions since we updated today
    compinit -C
  fi
}
_compinit
'''

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ['{{ name }}.zsh']

[plugins.F-Sy-H]
github = "z-shell/F-Sy-H"
