[global]
target = "~/.local/bin"

["ClementTsang/bottom"]
all = true
asset_filters = ["^musl", "^2-17"]

["sharkdp/bat"]
asset_filters = ["^musl"]

["bootandy/dust"]
asset_filters = ["^musl"]

["imsnif/bandwhich"]
asset_filters = ["^musl"]

["eza-community/eza"]
asset_filters = ["^musl", "^.zip"]
