alias d="docker"
alias dr="docker run"
alias db="docker build"
alias dp="docker pull"
alias dc="docker compose"
alias dcb="docker compose build"
alias dcu="docker compose up"
alias dcd="docker compose down"
