[tools]
"aqua:ClementTsang/bottom" = "latest"
bat = "latest"
eza = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"

hyperfine = "latest"
jq = "latest"
duf = "latest"
starship = "latest"
"ubi:imsnif/bandwhich" = "latest"
"ubi:rossmacarthur/sheldon" = "latest"
"ubi:tldr-pages/tlrc" = { version = "latest", exe = "tldr" }
usage = "latest"
uv = "latest"
xh = "latest"
yq = "latest"
zoxide = "latest"

[settings]
disable_tools = ["python"]
