[tools]
bat = "latest"
eza = "latest"
"aqua:ClementTsang/bottom" = "latest"
dust = "latest"
"ubi:imsnif/bandwhich" = "latest"
starship = "latest"
usage = "latest"
hyperfine = "latest"
fd = "latest"
duf = "latest"
xh = "latest"
uv = "latest"
yq = "latest"
jq = "latest"
"ubi:rossmacarthur/sheldon" = "latest"
zoxide = "latest"
fzf = "latest"

[settings]
disable_tools = ["python"]
