"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"

[hostname]
disabled = true

[container]
format = '[$symbol]($style) '
style = 'green bold dimmed'

[python]
disabled = true

[custom.uv]
command = 'get_python_version'
when = 'find_python_project'
style = 'yellow bold'
symbol = '🐍 '
format = 'via [$symbol($output )]($style)'
